# Generated by Django 2.1.5 on 2019-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('username', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(choices=[('PE', 'Pepperoni'), ('SA', 'Sausage'), ('MU', 'Mushrooms'), ('ON', 'Onions'), ('HA', 'Ham'), ('CA', 'Canadian Bacon'), ('PI', 'Pineapple'), ('EG', 'Eggplant'), ('TO', 'Tomato & Basil'), ('GR', 'Green Peppers'), ('HM', 'Hamburger'), ('SP', 'Spinach'), ('AR', 'Artichoke'), ('BU', 'Buffalo Chicken'), ('BA', 'Barbecue Chicken'), ('AN', 'Anchovies'), ('BL', 'Black Olives'), ('FR', 'Fresh Garlic'), ('ZU', 'Zucchini')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=48)),
                ('size', models.CharField(choices=[('L', 'Large'), ('S', 'Small'), ('N', 'None')], max_length=1)),
                ('cheese', models.BooleanField()),
                ('topping_ct', models.IntegerField()),
                ('price', models.FloatField()),
                ('pizza_toppings', models.ManyToManyField(blank=True, related_name='pizza_toppings', to='orders.PizzaT')),
            ],
        ),
        migrations.CreateModel(
            name='SubT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(choices=[('P', 'Mushrooms'), ('G', 'Green Peppers'), ('O', 'Onions')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_toppings',
            field=models.ManyToManyField(blank=True, related_name='sub_toppings', to='orders.SubT'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='orders.Product'),
        ),
    ]
