# Generated by Django 2.1.5 on 2019-10-07 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pizza_toppings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_toppings',
        ),
        migrations.AddField(
            model_name='product',
            name='ptoppings',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='orders.PizzaT'),
        ),
        migrations.AddField(
            model_name='product',
            name='stoppings',
            field=models.ManyToManyField(blank=True, related_name='subs', to='orders.SubT'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
